package main

import (
	"log"
	"net/http"
	"os"

	_ "my-solution/docs" // docs is generated by Swag CLI
	"my-solution/internal/api"
	"my-solution/internal/catalog"
	"my-solution/internal/store"

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title Favorites API
// @version 0.1
// @description API for managing user's favorite assets
// @host localhost:8080
// @BasePath /
func main() {
	// Get configuration from environment
	port := getEnv("PORT", "8080")
	catalogPath := getEnv("CATALOG_PATH", "sample_data/seed_assets.json")
	instanceID := getEnv("INSTANCE_ID", "default")

	log.Printf("Starting server: instance=%s, port=%s", instanceID, port)

	// Initialize global asset catalog
	catalog.Initialize()
	if err := catalog.Global.LoadFromFile(catalogPath); err != nil {
		log.Fatalf("Failed to load asset catalog: %v", err)
	}
	log.Printf("Loaded %d assets from catalog", catalog.Global.Count())

	// Initialize store - using MemoryStore for simplicity
	storeImpl := store.NewMemoryStore()
	log.Println("Using MemoryStore")

	// Initialize API server
	apiServer := &api.API{Store: storeImpl}

	r := mux.NewRouter()
	apiServer.RegisterHandlers(r)

	// Swagger UI
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	log.Printf("Server ready at :%s", port)
	if err := http.ListenAndServe(":"+port, r); err != nil {
		log.Fatalf("Could not start server: %v", err)
	}
}

// getEnv gets an environment variable with a default fallback
func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}
